server:
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: zc070306
  database: forum_system
  charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0